### ISSUE TITLE
Can't run the example code locally

### ISSUE THREAD

**Issue by TWry** [PacktPublishing/Mobx-QuickStart-Guide#1]
When I clone the repository, install the dependencies and do `npm run start`, I'm getting the following error:

`Module not found: Can't resolve '../chapter-03' in '/Users/user1/development/MobX-Quick-Start-Guide/src/core'`

**Comment by pavanpodila** [comment]
Thanks for catching it @TWry. This has been fixed with f43c845. Cheers!
