### ISSUE TITLE
Can't `npm install` due to missing package

### ISSUE THREAD

**Issue by cleathers** [PacktPublishing/Mobx-QuickStart-Guide#3]
The `package-lock.json` includes a reference to a dependency which doesn't seem to exist on npmjs.com anymore.

npm ERR! code E404
npm ERR! 404 Not Found: har-validator@https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz

It looks like `5.1.2` isn't available as a version for this package anymore. It seems as though it skips from `5.1.0` -> `5.1.3`

https://www.npmjs.com/package/har-validator

This seems to be the offending line. https://github.com/PacktPublishing/MobX-Quick-Start-Guide/blob/master/package-lock.json#L6939

It looks like it's required by way of `request`. Although I see two different versions of `har-validator`

**Comment by archiewald** [comment]
Hi @cleathers, had the same issue. It is related to https://github.com/ahmadnassri/node-har-validator/issues/113 I think. Just deleted the faulty `har-validator 5.1.2` entry from `package-lock.json` and run `npm install` so the package bumped. See https://github.com/PacktPublishing/MobX-Quick-Start-Guide/pull/4

**Comment by cleathers** [comment]
I cloned @archiewald's fork, ran the `npm install` and that worked perfectly. Followed it up with `npm start` and was able to see the book app running locally. I'd say that his fix seems to do the trick 👍
